In [1]:
import numpy as np
np.random.seed(7)
cities = np.array(["Kathmandu", "Pokhara", "Biratnagar", "Lalitpur", "Birgunj"])
days = np.array([f"D{i:02d}" for i in range(1, 15)])
temps = np.random.randint(14, 36, size=(5, 14)).astype(float) # °C, 5 cities × 14 days
humidity = np.random.randint(40, 95, size=(5, 14)).astype(float) # %
temps[2, 5] = np.nan # sensor outage
temps[4, 11] = np.nan

## B1 — Array anatomy and reshaping (3 pts)

Print `temps.shape` , `.ndim` , `.dtype` , `.size` . Then build `np.arange(70)` , reshape it to the same shape as `temps` two ways — with explicit dimensions and with `-1` — show the two results are identical, and flatten it back. In a comment, explain what `-1` asked NumPy to work out, and why reshaping does not copy the data.

In [11]:
print("B1 - temps shape:", temps.shape)
print("B1 - temps dimensions:", temps.ndim)
print("B1 - temps dtype:", temps.dtype)
print("B1 - temps size:", temps.size)

arr = np.arange(70)

reshaped_explicit = arr.reshape(5, 14)
reshaped_auto = arr.reshape(-1, 14)

print("B1 — Explicit reshape:")
print(reshaped_explicit)

print("B1 — Reshape using -1:")
print(reshaped_auto)

print("B1 — Are both reshapes identical:", np.array_equal(
    reshaped_explicit, reshaped_auto
))

flattened = reshaped_explicit.flatten()

print("B1 — Flattened array:")
print(flattened)

# -1 tells NumPy to automatically calculate the missing dimension based on
# the original size and the provided dimensions.
# Reshaping usually does not copy data because NumPy creates a new view that
# changes the way the same memory is interpreted.

B1 - temps shape: (5, 14)
B1 - temps dimensions: 2
B1 - temps dtype: float64
B1 - temps size: 70
B1 — Explicit reshape:
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20 21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34 35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63 64 65 66 67 68 69]]
B1 — Reshape using -1:
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20 21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34 35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63 64 65 66 67 68 69]]
B1 — Are both reshapes identical: True
B1 — Flattened array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


## B2 — Indexing and slicing (4 pts)

Using indexing and slicing only, print: (a) Pokhara's day-3 temperature; (b) every city's reading on the last day; (c) Biratnagar's full fortnight; (d) the block of the first three cities across days 4–8; (e) every other day for Lalitpur; (f) Kathmandu's fortnight reversed. Print the shape alongside each result.

In [12]:
print("B2a — Pokhara day-3 temperature:",
      temps[1, 2],
      "shape:", np.shape(temps[1, 2]))

print("B2b — Every city's reading on last day:",
      temps[:, -1],
      "shape:", temps[:, -1].shape)

print("B2c — Biratnagar full fortnight:",
      temps[2, :],
      "shape:", temps[2, :].shape)

print("B2d — First three cities across days 4–8:",
      temps[:3, 3:8],
      "shape:", temps[:3, 3:8].shape)

print("B2e — Every other day for Lalitpur:",
      temps[3, ::2],
      "shape:", temps[3, ::2].shape)

print("B2f — Kathmandu fortnight reversed:",
      temps[0, ::-1],
      "shape:", temps[0, ::-1].shape)

B2a — Pokhara day-3 temperature: 14.0 shape: ()
B2b — Every city's reading on last day: [30. 28. 21. 18. 30.] shape: (5,)
B2c — Biratnagar full fortnight: [20. 18. 28. 23. 17. nan 22. 33. 30. 15. 14. 30. 26. 21.] shape: (14,)
B2d — First three cities across days 4–8: [[33. 21. 28. 22. 28.]
 [25. 20. 33. 26. 19.]
 [23. 17. nan 22. 33.]] shape: (3, 5)
B2e — Every other day for Lalitpur: [24. 17. 21. 35. 17. 17. 33.] shape: (7,)
B2f — Kathmandu fortnight reversed: [30. 18. 20. 21. 22. 24. 28. 22. 28. 21. 33. 17. 18. 29.] shape: (14,)


## B3 — Boolean masks (3 pts)

(a) Build the mask `temps > 30` and print how many readings exceed 30 per city — one number per city, no loop. (b) Print the actual day labels on which Kathmandu exceeded 30, by using the mask to index `days` . (c) In a comment, explain in one sentence what a mask is, and why `temps[temps > 30]` cannot keep the 2D shape.

In [13]:
hot_mask = temps > 30

count_hot_per_city = np.sum(hot_mask, axis=1)

print("B3a — Readings above 30 per city:",
      count_hot_per_city)

kathmandu_hot_days = days[hot_mask[0]]

print("B3b — Kathmandu days above 30:",
      kathmandu_hot_days)

# A NumPy mask is a True/False filter.
# It picks elements that satisfy a condition, e.g., temps > 30, and can be used to index an array.
# The result becomes a 1D array because the number of matching elements can vary, so a fixed multidimensional shape cannot be maintained.
# Internally, Boolean indexing creates a new array containing the selected elements in iteration order.

B3a — Readings above 30 per city: [1 2 1 2 6]
B3b — Kathmandu days above 30: ['D04']


## B4 — Views vs. copies (3 pts)

Take a slice of one city's first three days, set its first element to `999` , and print the original array to prove it changed. Repeat with `.copy()` and prove it did not. In a comment, explain in two sentences why NumPy defaults to a view, and what bug this causes if you forget.

In [14]:
# Taking a slice (view)
city_slice = temps[0, :3]

city_slice[0] = 999

print("B4 — Original array after modifying view:")
print(temps[0])

# Using copy()
city_copy = temps[1, :3].copy()

city_copy[0] = 999

print("B4 — Original array after modifying copy:")
print(temps[1])

# NumPy defaults to views because they are faster and memory efficient since
# they avoid creating unnecessary copies of large arrays.
# Forgetting this can cause accidental changes to the original data when we
# modify a sliced array.

B4 — Original array after modifying view:
[999.  18.  17.  33.  21.  28.  22.  28.  24.  22.  21.  20.  18.  30.]
B4 — Original array after modifying copy:
[21. 26. 14. 25. 20. 33. 26. 19. 35. 30. 14. 16. 23. 28.]


## B5 — Vectorization vs. a Python loop (4 pts)

Convert `temps` to Fahrenheit two ways: with an explicit loop (the only loop allowed in Part B) and with one vectorized expression. Confirm they agree with `np.allclose` . Then time both on an array of 1,000,000 values using `time.perf_counter()` , and print both timings plus the speedup as a multiple ( ~Nx faster ). In a comment, explain where the loop's extra time actually goes.

In [17]:
import time

# Explicit Python loop  

fahrenheit_loop = np.empty_like(temps)

for i in range(temps.shape[0]):
    for j in range(temps.shape[1]):
        fahrenheit_loop[i, j] = (temps[i, j] * 9/5) + 32


# Vectorized NumPy method

fahrenheit_vectorized = (temps * 9/5) + 32


print("B5 — Loop and vectorized results agree:",
      np.allclose(fahrenheit_loop, fahrenheit_vectorized))


# Timing comparison on 1,000,000 values

large_array = np.random.randint(14, 36, size=1000000).astype(float)

start = time.perf_counter()

large_loop_result = np.empty_like(large_array)

for i in range(len(large_array)):
    large_loop_result[i] = (large_array[i] * 9/5) + 32

loop_time = time.perf_counter() - start


start = time.perf_counter()

large_vectorized_result = (large_array * 9/5) + 32

vectorized_time = time.perf_counter() - start


speedup = loop_time / vectorized_time

print("B5 - Loop timing:", loop_time, "seconds")
print("B5 - Vectorized timing:", vectorized_time, "seconds")
print("B5 - Vectorization speedup:", speedup, "x faster")


# The loop spends extra time repeatedly executing Python-level operations,
# indexing, and interpreter overhead for every element, while NumPy performs
# calculations using optimized compiled C operations internally.

B5 — Loop and vectorized results agree: False
B5 - Loop timing: 0.2890808999945875 seconds
B5 - Vectorized timing: 0.0056619000097271055 seconds
B5 - Vectorization speedup: 51.05722451790892 x faster


## B6 — Broadcasting (4 pts)

(a) Compute each city's own fortnight average with a NaN-aware function and `keepdims=True` , then subtract it from `temps` to get an anomaly grid; print the result's shape and confirm it is still `(5, 14)` . (b) Apply a per-day sensor correction of shape `(14,)` to all five cities in one expression. (c) Attempt `temps + np.array([1, 2, 3, 4, 5])` , catch the `ValueError` , print its message, and explain in a comment why aligning shapes from the right makes this fail while (b) succeeds.

In [18]:
# (a) City-wise fortnight average

city_average = np.nanmean(temps, axis=1, keepdims=True)

anomaly_grid = temps - city_average

print("B6a - Anomaly grid:")
print(anomaly_grid)

print("B6a - Anomaly grid shape:",
      anomaly_grid.shape)

print("B6a - Shape confirmation:",
      anomaly_grid.shape == (5, 14))


# (b) Per-day sensor correction

sensor_correction = np.array(
    [0.5, -0.2, 0.1, 0.3, -0.4, 0.2, 0.6,
     -0.1, 0.4, -0.3, 0.5, 0.2, -0.2, 0.1]
)

corrected_temps = temps + sensor_correction

print("B6b - Corrected temperature grid shape:",
      corrected_temps.shape)


# (c) Broadcasting error example

try:
    result = temps + np.array([1, 2, 3, 4, 5])

except ValueError as error:
    print("B6c - ValueError message:")
    print(error)


# Broadcasting compares shapes from the right side.
# In (b), (5,14) and (14,) match because 14 aligns with 14 columns.
# In (c), (5,14) and (5,) fail because 14 cannot align with 5.

B6a - Anomaly grid:
[[ 9.06071429e+02 -7.49285714e+01 -7.59285714e+01 -5.99285714e+01
  -7.19285714e+01 -6.49285714e+01 -7.09285714e+01 -6.49285714e+01
  -6.89285714e+01 -7.09285714e+01 -7.19285714e+01 -7.29285714e+01
  -7.49285714e+01 -6.29285714e+01]
 [-2.57142857e+00  2.42857143e+00 -9.57142857e+00  1.42857143e+00
  -3.57142857e+00  9.42857143e+00  2.42857143e+00 -4.57142857e+00
   1.14285714e+01  6.42857143e+00 -9.57142857e+00 -7.57142857e+00
  -5.71428571e-01  4.42857143e+00]
 [-2.84615385e+00 -4.84615385e+00  5.15384615e+00  1.53846154e-01
  -5.84615385e+00             nan -8.46153846e-01  1.01538462e+01
   7.15384615e+00 -7.84615385e+00 -8.84615385e+00  7.15384615e+00
   3.15384615e+00 -1.84615385e+00]
 [ 3.92857143e+00  2.92857143e+00 -3.07142857e+00 -6.07142857e+00
   9.28571429e-01 -6.07142857e+00  1.49285714e+01 -2.07142857e+00
  -3.07142857e+00 -5.07142857e+00 -3.07142857e+00 -5.07142857e+00
   1.29285714e+01 -2.07142857e+00]
 [ 6.46153846e+00 -1.15384615e+01 -7.53846154e+0

## B7 — Matrix multiplication (4 pts)

(a) On the grocery-basket example ( `quantities = [2, 3, 1]` , `prices = [120, 90, 250]` ), print both `*` and `@` , and state in a comment what each returned and why they differ. (b) Build `features` of shape `(14, 2)` whose columns are the across-city NaN-aware mean temperature and mean humidity per day, define `weights = np.array([0.6, -0.1])` , and compute a comfort score per day with `@` . Print the shapes of `features` , `weights` , and the result, and explain in a comment why the inner dimensions had to match.

In [19]:
# (a) Grocery basket example

quantities = np.array([2, 3, 1])
prices = np.array([120, 90, 250])

print("B7a — Element-wise multiplication (*):",
      quantities * prices)

print("B7a — Matrix multiplication (@):",
      quantities @ prices)


# * performs element-by-element multiplication and returns an array.
# @ performs dot product multiplication and returns a single scalar value
# because it sums the products of corresponding elements.


# (b) Comfort score calculation

mean_temp_per_day = np.nanmean(temps, axis=0)
mean_humidity_per_day = np.nanmean(humidity, axis=0)

features = np.column_stack(
    (mean_temp_per_day, mean_humidity_per_day)
)

weights = np.array([0.6, -0.1])

comfort_score = features @ weights


print("B7b — Features shape:",
      features.shape)

print("B7b — Weights shape:",
      weights.shape)

print("B7b — Comfort score shape:",
      comfort_score.shape)


# The inner dimensions must match because matrix multiplication requires the
# number of columns in the first array to equal the number of rows in the second.
# Here features has shape (14,2) and weights has shape (2,), so multiplication
# is valid.

B7a — Element-wise multiplication (*): [240 270 250]
B7a — Matrix multiplication (@): 760
B7b — Features shape: (14, 2)
B7b — Weights shape: (2,)
B7b — Comfort score shape: (14,)


## B8 — Aggregating along an axis (4 pts)

Using NaN-aware aggregations, print: mean, max, min and std per city; mean and max per day; and each city's hottest day as a day label (use `argmax` , then index `days` ). State each result's shape. In a comment, state what `axis=0` and `axis=1` collapse here, in terms of this dataset.

In [20]:
# Per city statistics

city_mean = np.nanmean(temps, axis=1)
city_max = np.nanmax(temps, axis=1)
city_min = np.nanmin(temps, axis=1)
city_std = np.nanstd(temps, axis=1)

print("B8 — Mean temperature per city:",
      city_mean,
      "shape:", city_mean.shape)

print("B8 — Maximum temperature per city:",
      city_max,
      "shape:", city_max.shape)

print("B8 — Minimum temperature per city:",
      city_min,
      "shape:", city_min.shape)

print("B8 — Standard deviation per city:",
      city_std,
      "shape:", city_std.shape)



# Per day statistics

day_mean = np.nanmean(temps, axis=0)
day_max = np.nanmax(temps, axis=0)

print("B8 — Mean temperature per day:",
      day_mean,
      "shape:", day_mean.shape)

print("B8 — Maximum temperature per day:",
      day_max,
      "shape:", day_max.shape)



# Hottest day for each city

hottest_day_index = np.nanargmax(temps, axis=1)

hottest_days = days[hottest_day_index]

print("B8 — Hottest day label for each city:",
      hottest_days,
      "shape:", hottest_days.shape)


# axis=0 collapses rows (cities), producing values for each day.
# axis=1 collapses columns (days), producing values for each city.

B8 — Mean temperature per city: [92.92857143 23.57142857 22.84615385 20.07142857 26.53846154] shape: (5,)
B8 — Maximum temperature per city: [999.  35.  33.  35.  35.] shape: (5,)
B8 — Minimum temperature per city: [17. 14. 14. 14. 15.] shape: (5,)
B8 — Standard deviation per city: [251.3422437    6.41108733   5.89453663   6.41943796   7.11028924] shape: (5,)
B8 — Mean temperature per day: [219.4   20.    19.    23.6   22.    22.75  27.6   26.    27.6   23.4
  16.6   20.25  25.8   25.4 ] shape: (14,)
B8 — Maximum temperature per day: [999.  26.  28.  33.  31.  33.  35.  33.  35.  35.  21.  30.  33.  30.] shape: (14,)
B8 — Hottest day label for each city: ['D01' 'D09' 'D08' 'D07' 'D10'] shape: (5,)


## B9 — Reproducible randomness and a train/test split (3 pts)

Flatten `temps` to 70 samples. With `np.random.seed(42)` , shuffle an index array and split it 80/20 into train and test index sets; print both shapes, confirm they sum to 70, and confirm they share no index. Re-seed with 42, repeat, and assert the split is identical. In a comment, explain why you shuffle before splitting, and why the seed matters when you share results.

In [ ]:
samples = temps.flatten()

indices = np.arange(samples.size)

np.random.seed(42)

np.random.shuffle(indices)

train_indices = indices[:56]
test_indices = indices[56:]


print("B9 - Training index shape:",
      train_indices.shape)

print("B9 - Testing index shape:",
      test_indices.shape)

print("B9 - Total samples:",
      train_indices.size + test_indices.size)

print("B9 - Shared indexes:",
      np.intersect1d(train_indices, test_indices).size == 0)



# Repeat with the same seed

np.random.seed(42)

indices_repeat = np.arange(samples.size)

np.random.shuffle(indices_repeat)

train_repeat = indices_repeat[:56]
test_repeat = indices_repeat[56:]


assert np.array_equal(train_indices, train_repeat)
assert np.array_equal(test_indices, test_repeat)

print("B9 - Split identical after reseeding:",
      True)


# Shuffling before splitting prevents the train and test sets from containing
# biased groups of ordered data.
# The seed ensures the random process produces the same split when results are
# shared or experiments are repeated.

B9 — Training index shape: (56,)
B9 — Testing index shape: (14,)
B9 — Total samples: 70
B9 — Shared indexes: True
B9 — Split identical after reseeding: True


## B10 — np.where , argmax , argmin (3 pts)

(a) Label every reading "hot" / "mild" / "cold" (above 30, 22–30, below 22) with nested `np.where` , and print the label grid's shape. (b) Given `scores = np.array([0.08, 0.62, 0.21, 0.09])` and `labels = ["rain", "clear", "cloudy", "fog"]` , print the predicted label using `argmax` . In a comment, explain why a classifier needs `argmax` rather than `max`

In [22]:
# (a) Temperature labels

temperature_labels = np.where(
    temps > 30,
    "hot",
    np.where(
        temps >= 22,
        "mild",
        "cold"
    )
)

print("B10a - Temperature label grid:")
print(temperature_labels)

print("B10a - Label grid shape:",
      temperature_labels.shape)



# (b) Prediction using argmax

scores = np.array([0.08, 0.62, 0.21, 0.09])

labels = np.array(["rain", "clear", "cloudy", "fog"])

predicted_label = labels[np.argmax(scores)]

print("B10b - Predicted label:",
      predicted_label)


# A classifier needs argmax because it returns the position of the highest
# probability score, which allows us to select the corresponding class label.
# max only returns the highest value and loses the class information.

B10a - Temperature label grid:
[['hot' 'cold' 'cold' 'hot' 'cold' 'mild' 'mild' 'mild' 'mild' 'mild'
  'cold' 'cold' 'cold' 'mild']
 ['cold' 'mild' 'cold' 'mild' 'cold' 'hot' 'mild' 'cold' 'hot' 'mild'
  'cold' 'cold' 'mild' 'mild']
 ['cold' 'cold' 'mild' 'mild' 'cold' 'cold' 'mild' 'hot' 'mild' 'cold'
  'cold' 'mild' 'mild' 'cold']
 ['mild' 'mild' 'cold' 'cold' 'cold' 'cold' 'hot' 'cold' 'cold' 'cold'
  'cold' 'cold' 'hot' 'cold']
 ['hot' 'cold' 'cold' 'mild' 'hot' 'cold' 'hot' 'hot' 'hot' 'hot' 'cold'
  'cold' 'mild' 'mild']]
B10a - Label grid shape: (5, 14)
B10b - Predicted label: clear
